name: Mirror GitHub Pages from Another Repo

on:
  schedule:
    - cron: "0 * * * *"  # every hour
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout destination repo (this repo)
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Clone source repo
        run: |
          git clone --depth 1 https://github.com/tycho10101/tycho10101.is-a.dev.git source
          rm -rf ./*
          cp -r source/* ./
          rm -rf source

      - name: Configure git and push changes
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git diff --cached --quiet || git commit -m "Mirror update"
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
          git push
