name: Mirror GitHub Pages from Another Repo (with replacement)

on:
  schedule:
    - cron: "0 * * * *"  # every hour
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout destination repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          
      - name: Clone source repo
        run: |
          git clone --depth 1 https://x-access-token:${{ secrets.SOURCE_REPO_TOKEN }}@github.com/Tycho10101/tycho10101.github.io.git source
          if [ ! "$(ls -A source)" ]; then
              echo "Source repository is empty or cloning failed."
              exit 1
          fi
          rm -rf ./*
          rsync -a source/ ./
          rm -rf source

      - name: Replace text in all files
        run: |
          find . -type f -exec sed -i 's|https://tycho10101.is-a.dev|https://tycho10101.is-a.dev/site-mirror|g' {} +
          find . -type f -exec sed -i 's|https://tycho10101.github.io|https://tycho10101.is-a.dev/site-mirror|g' {} +

      - name: Configure git and push changes
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git diff --cached --quiet || git commit -m "Mirror update with replaced text"
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
          git push
